language: node_js
node_js: stable

install:
  - npm install

script:
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "${Author}"
  - git config user.email "${Email}"
  - git add .
  - git commit -m "[release]: update blog from travis ci"
  - git push --force --quiet "https://${GitHubToken}@${RepoRef}" master:master

branches:
  only:
    - hexo
